---
# tasks file for kubeadm

- name: Get kubelet version
  ansible.builtin.command:
    cmd: kubelet --version
  register: kubelet_version

- name: Create kubeadm configuration file
  become: true
  ansible.builtin.template:
    src: etc/kubernetes/kubeadm_init.yaml.j2
    dest: /etc/kubernetes/kubeadm_init.yaml

- name: Kubeadm init
  become: true
  ansible.builtin.command:
    cmd: kubeadm init --config=/etc/kubernetes/kubeadm_init.yaml
  register: kubeadm_init

- name: Create .kube directory
  become: true
  ansible.builtin.file:
    path: /root/.kube
    state: directory
    mode: '0700'

- name: Copy admin.conf to .kube directory
  become: true
  ansible.builtin.copy:
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config
    remote_src: yes
