all:
  hosts:
    k8s01:
      ansible_host: 192.168.1.155
    k8s02:
      ansible_host: 192.168.1.60
    k8s03:
      ansible_host: 192.168.1.229
  children:
    kube_control_plane:
      hosts:
        k8s01:
        k8s02:
        k8s03:
    kube_node:
      hosts:
        k8s01:
        k8s02:
        k8s03:
    etcd:
      hosts:
        k8s01:
        k8s02:
        k8s03:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
