- name: Ensure swap file does not already exist
  become: true
  ansible.builtin.stat:
    path: "{{ swap_file_path }}"
  register: swap_file_stat

- name: Create swap file
  become: true
  ansible.builtin.command: fallocate -l {{ common_swap_file_size }} {{ common_swap_file_path }}
  when: not swap_file_stat.stat.exists
  register: swap_file_create

- name: Set permissions on swap file
  become: true
  ansible.builtin.file:
    path: "{{ common_swap_file_path }}"
    owner: root
    group: root
    mode: '0600'
  when: swap_file_create is changed

- name: Initialize swap file
  become: true
  ansible.builtin.command: mkswap {{ common_swap_file_path }}
  when: swap_file_create is changed
  register: mkswap_result

- name: Enable swap file
  become: true
  command: swapon {{ common_swap_file_path }}
  when: mkswap_result is changed

- name: Set swappiness
  become: true
  ansible.builtin.sysctl:
    name: vm.swappiness
    value: "{{ common_swap_swappiness }}"
    state: present
