---
- name: Disable swap
  become: true
  ansible.builtin.command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: Ensure swap file doesn't exist
  become: true
  ansible.builtin.file:
    path: "{{ common_swap_file_path }}"
    state: absent
