- name: Create cache dir
  delegate_to: localhost
  run_once: true
  ansible.builtin.file:
    path: "{{ cri_containerd_cache_dir }}"
    state: directory

- name: Download containerd
  delegate_to: localhost
  run_once: true
  ansible.builtin.get_url:
    url: "{{ cri_containerd_release_url.replace('\n', '') }}"
    dest: "{{ cri_containerd_cache_dir }}/containerd.tar.gz"

- name: Download containerd systemd service file
  delegate_to: localhost
  run_once: true
  ansible.builtin.get_url:
    url: "{{ cri_containerd_systemd_file_url }}"
    dest: "{{ cri_containerd_cache_dir }}/containerd.service"

- name: Setup containerd in /usr/local
  ansible.builtin.unarchive:
    src: "{{ cri_containerd_cache_dir }}/containerd.tar.gz"
    dest: /usr/local

- name: Create containerd.service dir
  ansible.builtin.file:
    path: /usr/local/lib/systemd/system/
    state: directory

- name: Create containerd.service
  ansible.builtin.copy:
    src: "{{ cri_containerd_cache_dir }}/containerd.service"
    dest: /usr/local/lib/systemd/system/containerd.service
    owner: root
    group: root
    mode: '0644'

# Continue from: https://github.com/containerd/containerd/blob/main/docs/getting-started.md#step-2-installing-runc