---
# tasks file for runc
- name: Create cache dir
  delegate_to: localhost
  run_once: true
  ansible.builtin.file:
    path: "{{ oci_runc_cache_dir }}"
    state: directory
    mode: '0755'

- name: Download runc
  delegate_to: localhost
  run_once: true
  ansible.builtin.get_url:
    url: "{{ oci_runc_release_url.replace('\n', '') }}"
    dest: "{{ oci_runc_cache_dir }}/runc.amd64"
    mode: '0755'

- name: Setup runc
  ansible.builtin.copy:
    src: "{{ oci_runc_cache_dir }}/runc.amd64"
    dest: /usr/local/sbin/runc
    owner: root
    group: root
    mode: '0755'
