---
- name: Setup nodes
  hosts: all
  become: true
  roles:
    - facts
    - common
    - disable_swap
    - kubernetes/cri/containerd
    - kubernetes/oci/runc
    - kubernetes/core
  vars:
    cache_dir: /tmp/kubesmith
