all:
  hosts:
    k8s01:
      ansible_host: 192.168.4.3
  children:
    kube_control_plane:
      hosts:
        k8s01:
    kube_node:
      hosts:
        k8s01:
    etcd:
      hosts:
        k8s01:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
